"""Add quality scores and image dimensions

Revision ID: 131fd44199da
Revises: f05bc7373a80
Create Date: 2026-01-25 16:22:04.589884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131fd44199da'
down_revision: Union[str, None] = 'f05bc7373a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('image_pixel_width', sa.Integer(), nullable=True))
    op.add_column('artworks', sa.Column('image_pixel_height', sa.Integer(), nullable=True))
    op.add_column('artworks', sa.Column('quality_scores', sa.JSON(), nullable=True))
    op.add_column('artworks', sa.Column('quality_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'quality_score')
    op.drop_column('artworks', 'quality_scores')
    op.drop_column('artworks', 'image_pixel_height')
    op.drop_column('artworks', 'image_pixel_width')
    # ### end Alembic commands ###
