"""Initial database setup

Revision ID: 35b8505c9f6f
Revises: 
Create Date: 2024-11-25 19:03:23.306073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b8505c9f6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('artist', sa.String(length=500), nullable=True),
    sa.Column('artist_display', sa.String(length=500), nullable=True),
    sa.Column('date_created', sa.String(length=100), nullable=True),
    sa.Column('medium', sa.String(length=500), nullable=True),
    sa.Column('dimensions', sa.String(length=500), nullable=True),
    sa.Column('credit_line', sa.String(length=1000), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_public_domain', sa.Boolean(), nullable=True),
    sa.Column('is_highlight', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('museum_id', 'original_id', name='unique_artwork_per_museum')
    )
    op.create_index('ix_artwork_artist', 'artworks', ['artist'], unique=False)
    op.create_index('ix_artwork_title', 'artworks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artwork_title', table_name='artworks')
    op.drop_index('ix_artwork_artist', table_name='artworks')
    op.drop_table('artworks')
    op.drop_table('museums')
    # ### end Alembic commands ###
