"""Reset schema with expanded artwork metadata

Revision ID: f05bc7373a80
Revises: 
Create Date: 2024-11-30 11:23:44.079255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05bc7373a80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.String(length=50), nullable=False),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('artist', sa.String(length=500), nullable=True),
    sa.Column('artist_display', sa.String(length=500), nullable=True),
    sa.Column('artist_bio', sa.Text(), nullable=True),
    sa.Column('artist_nationality', sa.String(length=100), nullable=True),
    sa.Column('artist_birth_year', sa.Integer(), nullable=True),
    sa.Column('artist_death_year', sa.Integer(), nullable=True),
    sa.Column('date_display', sa.String(length=100), nullable=True),
    sa.Column('date_start', sa.String(length=50), nullable=True),
    sa.Column('date_end', sa.String(length=50), nullable=True),
    sa.Column('medium', sa.String(length=500), nullable=True),
    sa.Column('dimensions', sa.String(length=500), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('depth_cm', sa.Float(), nullable=True),
    sa.Column('diameter_cm', sa.Float(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('artwork_type', sa.String(length=100), nullable=True),
    sa.Column('culture', sa.JSON(), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('is_public_domain', sa.Boolean(), nullable=True),
    sa.Column('credit_line', sa.Text(), nullable=True),
    sa.Column('is_on_view', sa.Boolean(), nullable=True),
    sa.Column('is_highlight', sa.Boolean(), nullable=True),
    sa.Column('is_boosted', sa.Boolean(), nullable=True),
    sa.Column('boost_rank', sa.Integer(), nullable=True),
    sa.Column('has_not_been_viewed_much', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('inscriptions', sa.JSON(), nullable=True),
    sa.Column('fun_fact', sa.Text(), nullable=True),
    sa.Column('style_titles', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('primary_image_url', sa.String(length=1000), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(length=1000), nullable=True),
    sa.Column('colorfulness', sa.Float(), nullable=True),
    sa.Column('color_h', sa.Integer(), nullable=True),
    sa.Column('color_s', sa.Integer(), nullable=True),
    sa.Column('color_l', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('museum_id', 'original_id', name='unique_artwork_per_museum')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artworks')
    op.drop_table('museums')
    # ### end Alembic commands ###
